FROM app

RUN set -x \
    # requirements for cryptography (installed by ansible)
    && apk add --no-cache build-base libressl-dev musl-dev libffi-dev \
    # requirements for ansible
    && apk add --no-cache openssh-client sshpass \
    # requirements for ansible-uptime-kuma
    && apk add --no-cache git

USER abc:abc

RUN set -x \
    && ansible-galaxy collection install git+https://github.com/lucasheld/ansible-uptime-kuma.git
